### ISSUE TITLE
Microsoft access Not working

### ISSUE THREAD

**Issue by asoftdb** [zingl/2D-Barcode#2]
thanks for this qrcode file accdb
but it's not working 
access 2021 - 32 bit - windows 10
![qr](https://user-images.githubusercontent.com/50542600/207263772-b3646bc4-ad0f-4b61-9c2e-acc069d4f02e.png)

working fine in excel
![qr2](https://user-images.githubusercontent.com/50542600/207263905-f052205b-a63c-475d-a6ab-645c2352d272.png)

**Comment by zingl** [comment]
The barcode in access is only drawn in page view.

**Comment by asoftdb** [comment]
> The barcode in access is only drawn in page view.

Sorry but it doesn't work in any mode

**Comment by asoftdb** [comment]
**in print preview** 
![qr](https://user-images.githubusercontent.com/50542600/207515657-ef656fb1-3004-4365-8096-fd9974415e91.png)

**Comment by asoftdb** [comment]
thanks now it's working after i recreate report
